version: '3.7'
services:
  web:
    build: ./nekidblog
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./nekidblog/:/usr/src/nekidblog/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=nekidalo
      - POSTGRES_PASSWORD=nekidaemru
      - POSTGRES_DB=nekidblog
volumes:
  postgres_data:
    
